# Generated by Django 3.0.3 on 2020-02-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='car_name',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='from_name',
            field=models.CharField(default='', max_length=25),
        ),
    ]
